services:
  fastapi:
    build: .
    container_name: deploy_FastResponseIntention  # Đặt tên cho container
    ports:
      - "25041:25041"  # Map cổng 25041 của host và container
    volumes:
      - ./trained_models:/app/trained_models  # Ánh xạ thư mục chứa mô hình
    environment:
      MODEL_PATH: "./trained_models/v7_trainsets_ckp-300_XLMRoBERTa_20eps"  # Truyền biến môi trường nếu cần
    restart: always  # Tự động khởi động lại container khi có lỗi